version: "3.7"

networks:
  default:
    driver: bridge

services:
  explorer:
    container_name: prcx-rpc-explorer
    #define $UID, $GID in .env file the user to run docker and write in data folder
    #user: "1000:1000"
    environment:
      PRCXEXP_HOST: 0.0.0.0
      PRCXEXP_PRICECOINXD_URI: $PRCXEXP_PRICECOINXD_URI
      PRCXEXP_ADDRESS_API: $PRCXEXP_ADDRESS_API
      PRCXEXP_ELECTRUM_SERVERS: $PRCXEXP_ELECTRUM_SERVERS
      PRCXEXP_SLOW_DEVICE_MODE: false
      #More information mode, including PricecoinX exchange rates
      #More privacy mode, no external queries
      # PRCXEXP_PRIVACY_MODE: true
      # PRCXEXP_NO_RATES: true
      # PRCXEXP_UI_THEME: dark
    build:
      context: ./
    image: prcx-rpc-explorer:latest
    #restart: "no"
    ports:
      - "3002:3002"
